name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run export
      
    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Commit and push dist folder
      run: |
        git add dist/
        git commit -m "Auto-build: Update dist folder [skip ci]" || echo "No changes to commit"
        git push origin main
        
    - name: Deploy to Hostinger (Optional)
      run: |
        echo "Build completed successfully!"
        echo "The dist folder has been updated in the repository."
        echo "You can now pull these changes on your Hostinger server."
